[INFO    ] 2018-10-30T15:39:22.999777256Z: Running Test linuxkit.kernel.kmod_4.19.x in /tmp/with_clone174b5482/test/cases/020_kernel/015_kmod_4.19.x
[INFO    ] 2018-10-30T15:39:23.000023392Z: Running command: [/bin/sh -x /tmp/with_clone174b5482/test/cases/020_kernel/015_kmod_4.19.x/test.sh]
[STDERR  ] 2018-10-30T15:39:23.000975344Z: + set -e
[STDERR  ] 2018-10-30T15:39:23.001058973Z: + . /tmp/with_clone174b5482/test/cases/_lib/lib.sh
[STDERR  ] 2018-10-30T15:39:23.001085241Z: + [ -f src/github.com/linuxkit/rtf/lib/lib.sh ]
[STDERR  ] 2018-10-30T15:39:23.001112100Z: + LINUXKIT_TMPDIR=/tmp/with_clone174b5482/test/cases/_tmp
[STDERR  ] 2018-10-30T15:39:23.001143320Z: + [ -f /tmp/with_clone174b5482/test/cases/_tmp/env.sh ]
[STDERR  ] 2018-10-30T15:39:23.001242233Z: + . /tmp/with_clone174b5482/test/cases/_tmp/env.sh
[STDERR  ] 2018-10-30T15:39:23.001277973Z: + export LINUXKIT_EXAMPLES_DIR=/tmp/with_clone174b5482/test/cases/../../examples
[STDERR  ] 2018-10-30T15:39:23.001309750Z: + RT_CANCEL=253
[STDERR  ] 2018-10-30T15:39:23.001335691Z: + NAME=kmod
[STDERR  ] 2018-10-30T15:39:23.001363969Z: + IMAGE_NAME=kmod-test
[STDERR  ] 2018-10-30T15:39:23.001410511Z: + trap clean_up EXIT
[STDERR  ] 2018-10-30T15:39:23.001437739Z: + docker pull linuxkit/kernel:4.19
[STDERR  ] 2018-10-30T15:39:25.806560243Z: Error response from daemon: received unexpected HTTP status: 503 Service Unavailable
[STDERR  ] 2018-10-30T15:39:25.808229477Z: + clean_up
[STDERR  ] 2018-10-30T15:39:25.808289160Z: + docker rmi kmod-test
[STDERR  ] 2018-10-30T15:39:25.828741656Z: Error response from daemon: No such image: kmod-test:latest
[STDERR  ] 2018-10-30T15:39:25.830163065Z: + true
[STDERR  ] 2018-10-30T15:39:25.830283789Z: + rm -rf kmod-*
[FAIL    ] linuxkit.kernel.kmod_4.19.x 2.83s
