Error was:

```
[2018-09-01 20:26.01] Running "/gcloud/destroy.py" "linuxkit-ci-0"
Traceback (most recent call last):
  File "/gcloud/destroy.py", line 3, in <module>
    import common
  File "/gcloud/common.py", line 3, in <module>
    from oauth2client.service_account import ServiceAccountCredentials
ImportError: No module named oauth2client.service_account
```

/cc @justincormack @rn